//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdverKeyword
    {
        public AdverKeyword()
        {
            this.FreeAdvertises = new HashSet<FreeAdvertise>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Wieght { get; set; }
    
        public virtual ICollection<FreeAdvertise> FreeAdvertises { get; set; }
    }
}
