//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentWorkflow
    {
        public ContentWorkflow()
        {
            this.ContentWorkflowLogs = new HashSet<ContentWorkflowLog>();
            this.ContentWorkflowStates = new HashSet<ContentWorkflowState>();
            this.Folders = new HashSet<Folder>();
        }
    
        public int WorkflowID { get; set; }
        public Nullable<int> PortalID_ { get; set; }
        public string WorkflowName { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public bool StartAfterCreating { get; set; }
        public bool StartAfterEditing { get; set; }
        public bool DispositionEnabled { get; set; }
    
        public virtual ICollection<ContentWorkflowLog> ContentWorkflowLogs { get; set; }
        public virtual ICollection<ContentWorkflowState> ContentWorkflowStates { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
    }
}
