//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentWorkflowLog
    {
        public int WorkflowLogID { get; set; }
        public string Action { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int User { get; set; }
        public int WorkflowID { get; set; }
        public int ContentItemID { get; set; }
    
        public virtual ContentItem ContentItem { get; set; }
        public virtual ContentWorkflow ContentWorkflow { get; set; }
    }
}
