//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentWorkflowState
    {
        public ContentWorkflowState()
        {
            this.ContentItems = new HashSet<ContentItem>();
            this.ContentWorkflowStatePermissions = new HashSet<ContentWorkflowStatePermission>();
        }
    
        public int StateID { get; set; }
        public int WorkflowID { get; set; }
        public string StateName { get; set; }
        public int Order { get; set; }
        public bool IsActive { get; set; }
        public bool SendEmail { get; set; }
        public bool SendMessage { get; set; }
        public bool IsDisposalState { get; set; }
        public string OnCompleteMessageSubject { get; set; }
        public string OnCompleteMessageBody { get; set; }
        public string OnDiscardMessageSubject { get; set; }
        public string OnDiscardMessageBody { get; set; }
    
        public virtual ICollection<ContentItem> ContentItems { get; set; }
        public virtual ContentWorkflow ContentWorkflow { get; set; }
        public virtual ICollection<ContentWorkflowStatePermission> ContentWorkflowStatePermissions { get; set; }
    }
}
