//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreMessaging_Messages
    {
        public CoreMessaging_Messages()
        {
            this.CoreMessaging_MessageAttachments = new HashSet<CoreMessaging_MessageAttachments>();
            this.CoreMessaging_MessageRecipients = new HashSet<CoreMessaging_MessageRecipients>();
        }
    
        public int MessageID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> ConversationID { get; set; }
        public Nullable<bool> ReplyAllAllowed { get; set; }
        public Nullable<int> SenderUserID { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Context { get; set; }
        public Nullable<bool> IncludeDismissAction { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    
        public virtual ICollection<CoreMessaging_MessageAttachments> CoreMessaging_MessageAttachments { get; set; }
        public virtual ICollection<CoreMessaging_MessageRecipients> CoreMessaging_MessageRecipients { get; set; }
        public virtual CoreMessaging_NotificationTypes CoreMessaging_NotificationTypes { get; set; }
    }
}
