//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreMessaging_Subscriptions
    {
        public int SubscriptionId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PortalId { get; set; }
        public int SubscriptionTypeId { get; set; }
        public string ObjectKey { get; set; }
        public string ObjectData { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> TabId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Portal Portal { get; set; }
        public virtual CoreMessaging_SubscriptionTypes CoreMessaging_SubscriptionTypes { get; set; }
        public virtual User User { get; set; }
    }
}
