//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmirhomeEntities : DbContext
    {
        public AmirhomeEntities()
            : base("name=AmirhomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<FreeAdvertise> FreeAdvertises { get; set; }
        public virtual DbSet<GoogleMap> GoogleMaps { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StateType> StateTypes { get; set; }
        public virtual DbSet<StreetView> StreetViews { get; set; }
        public virtual DbSet<tbl_cities> tbl_cities { get; set; }
        public virtual DbSet<UserAccouunt> UserAccouunts { get; set; }
        public virtual DbSet<UserAccouuntsRole> UserAccouuntsRoles { get; set; }
        public virtual DbSet<Affiliate> Affiliates { get; set; }
        public virtual DbSet<AnonymousUser> AnonymousUsers { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<Assembly> Assemblies { get; set; }
        public virtual DbSet<Authentication> Authentications { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<ContentItem> ContentItems { get; set; }
        public virtual DbSet<ContentItems_MetaData> ContentItems_MetaData { get; set; }
        public virtual DbSet<ContentItems_Tags> ContentItems_Tags { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<ContentWorkflowLog> ContentWorkflowLogs { get; set; }
        public virtual DbSet<ContentWorkflow> ContentWorkflows { get; set; }
        public virtual DbSet<ContentWorkflowStatePermission> ContentWorkflowStatePermissions { get; set; }
        public virtual DbSet<ContentWorkflowState> ContentWorkflowStates { get; set; }
        public virtual DbSet<CoreMessaging_MessageAttachments> CoreMessaging_MessageAttachments { get; set; }
        public virtual DbSet<CoreMessaging_MessageRecipients> CoreMessaging_MessageRecipients { get; set; }
        public virtual DbSet<CoreMessaging_Messages> CoreMessaging_Messages { get; set; }
        public virtual DbSet<CoreMessaging_NotificationTypeActions> CoreMessaging_NotificationTypeActions { get; set; }
        public virtual DbSet<CoreMessaging_NotificationTypes> CoreMessaging_NotificationTypes { get; set; }
        public virtual DbSet<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual DbSet<CoreMessaging_SubscriptionTypes> CoreMessaging_SubscriptionTypes { get; set; }
        public virtual DbSet<CoreMessaging_UserPreferences> CoreMessaging_UserPreferences { get; set; }
        public virtual DbSet<Dashboard_Controls> Dashboard_Controls { get; set; }
        public virtual DbSet<DesktopModulePermission> DesktopModulePermissions { get; set; }
        public virtual DbSet<DesktopModule> DesktopModules { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<EventLogConfig> EventLogConfigs { get; set; }
        public virtual DbSet<EventLogType> EventLogTypes { get; set; }
        public virtual DbSet<EventQueue> EventQueues { get; set; }
        public virtual DbSet<ExtensionUrlProviderConfiguration> ExtensionUrlProviderConfigurations { get; set; }
        public virtual DbSet<ExtensionUrlProvider> ExtensionUrlProviders { get; set; }
        public virtual DbSet<ExtensionUrlProviderSetting> ExtensionUrlProviderSettings { get; set; }
        public virtual DbSet<ExtensionUrlProviderTab> ExtensionUrlProviderTabs { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileVersion> FileVersions { get; set; }
        public virtual DbSet<FolderMapping> FolderMappings { get; set; }
        public virtual DbSet<FolderMappingsSetting> FolderMappingsSettings { get; set; }
        public virtual DbSet<FolderPermission> FolderPermissions { get; set; }
        public virtual DbSet<Folder> Folders { get; set; }
        public virtual DbSet<HostSetting> HostSettings { get; set; }
        public virtual DbSet<HtmlText> HtmlTexts { get; set; }
        public virtual DbSet<HtmlTextLog> HtmlTextLogs { get; set; }
        public virtual DbSet<HtmlTextUser> HtmlTextUsers { get; set; }
        public virtual DbSet<IPFilter> IPFilters { get; set; }
        public virtual DbSet<JavaScriptLibrary> JavaScriptLibraries { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Journal_Access> Journal_Access { get; set; }
        public virtual DbSet<Journal_Comments> Journal_Comments { get; set; }
        public virtual DbSet<Journal_Data> Journal_Data { get; set; }
        public virtual DbSet<Journal_Security> Journal_Security { get; set; }
        public virtual DbSet<Journal_TypeFilters> Journal_TypeFilters { get; set; }
        public virtual DbSet<Journal_Types> Journal_Types { get; set; }
        public virtual DbSet<LanguagePack> LanguagePacks { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Messaging_Messages> Messaging_Messages { get; set; }
        public virtual DbSet<MetaData> MetaDatas { get; set; }
        public virtual DbSet<Mobile_PreviewProfiles> Mobile_PreviewProfiles { get; set; }
        public virtual DbSet<Mobile_RedirectionRules> Mobile_RedirectionRules { get; set; }
        public virtual DbSet<Mobile_Redirections> Mobile_Redirections { get; set; }
        public virtual DbSet<ModuleControl> ModuleControls { get; set; }
        public virtual DbSet<ModuleDefinition> ModuleDefinitions { get; set; }
        public virtual DbSet<ModulePermission> ModulePermissions { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleSetting> ModuleSettings { get; set; }
        public virtual DbSet<PackageDependency> PackageDependencies { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageType> PackageTypes { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PortalAlia> PortalAlias { get; set; }
        public virtual DbSet<PortalDesktopModule> PortalDesktopModules { get; set; }
        public virtual DbSet<PortalGroup> PortalGroups { get; set; }
        public virtual DbSet<PortalLanguage> PortalLanguages { get; set; }
        public virtual DbSet<PortalLocalization> PortalLocalizations { get; set; }
        public virtual DbSet<Portal> Portals { get; set; }
        public virtual DbSet<PortalSetting> PortalSettings { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfilePropertyDefinition> ProfilePropertyDefinitions { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<RelationshipType> RelationshipTypes { get; set; }
        public virtual DbSet<RoleGroup> RoleGroups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleSetting> RoleSettings { get; set; }
        public virtual DbSet<RolesMng> RolesMngs { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleHistory> ScheduleHistories { get; set; }
        public virtual DbSet<ScheduleItemSetting> ScheduleItemSettings { get; set; }
        public virtual DbSet<SearchCommonWord> SearchCommonWords { get; set; }
        public virtual DbSet<SearchIndexer> SearchIndexers { get; set; }
        public virtual DbSet<SearchStopWord> SearchStopWords { get; set; }
        public virtual DbSet<SearchType> SearchTypes { get; set; }
        public virtual DbSet<SiteLog> SiteLogs { get; set; }
        public virtual DbSet<SkinControl> SkinControls { get; set; }
        public virtual DbSet<SkinPackage> SkinPackages { get; set; }
        public virtual DbSet<Skin> Skins { get; set; }
        public virtual DbSet<SQLQuery> SQLQueries { get; set; }
        public virtual DbSet<SynonymsGroup> SynonymsGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemMessage> SystemMessages { get; set; }
        public virtual DbSet<TabAliasSkin> TabAliasSkins { get; set; }
        public virtual DbSet<TabModule> TabModules { get; set; }
        public virtual DbSet<TabModuleSetting> TabModuleSettings { get; set; }
        public virtual DbSet<TabPermission> TabPermissions { get; set; }
        public virtual DbSet<Tab> Tabs { get; set; }
        public virtual DbSet<TabSetting> TabSettings { get; set; }
        public virtual DbSet<TabUrl> TabUrls { get; set; }
        public virtual DbSet<Taxonomy_ScopeTypes> Taxonomy_ScopeTypes { get; set; }
        public virtual DbSet<Taxonomy_Terms> Taxonomy_Terms { get; set; }
        public virtual DbSet<Taxonomy_Vocabularies> Taxonomy_Vocabularies { get; set; }
        public virtual DbSet<Taxonomy_VocabularyTypes> Taxonomy_VocabularyTypes { get; set; }
        public virtual DbSet<UrlLog> UrlLogs { get; set; }
        public virtual DbSet<Url> Urls { get; set; }
        public virtual DbSet<UrlTracking> UrlTrackings { get; set; }
        public virtual DbSet<UserAuthentication> UserAuthentications { get; set; }
        public virtual DbSet<UserPortal> UserPortals { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRelationshipPreference> UserRelationshipPreferences { get; set; }
        public virtual DbSet<UserRelationship> UserRelationships { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersOnline> UsersOnlines { get; set; }
        public virtual DbSet<VendorClassification> VendorClassifications { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<WebServer> WebServers { get; set; }
        public virtual DbSet<Workflow> Workflows { get; set; }
        public virtual DbSet<WorkflowState> WorkflowStates { get; set; }
    }
}
