//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreMessaging_MessageRecipients
    {
        public int RecipientID { get; set; }
        public int MessageID { get; set; }
        public int UserID { get; set; }
        public bool Read { get; set; }
        public bool Archived { get; set; }
        public bool EmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public Nullable<System.Guid> EmailSchedulerInstance { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public bool SendToast { get; set; }
    
        public virtual CoreMessaging_Messages CoreMessaging_Messages { get; set; }
    }
}
