//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionUrlProvider
    {
        public int ExtensionUrlProviderID { get; set; }
        public string ProviderName { get; set; }
        public string ProviderType { get; set; }
        public string SettingsControlSrc { get; set; }
        public bool IsActive { get; set; }
        public bool RewriteAllUrls { get; set; }
        public bool RedirectAllUrls { get; set; }
        public bool ReplaceAllUrls { get; set; }
        public Nullable<int> DesktopModuleId { get; set; }
    }
}
