//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JavaScriptLibrary
    {
        public int JavaScriptLibraryID { get; set; }
        public int PackageID { get; set; }
        public string LibraryName { get; set; }
        public string Version { get; set; }
        public string FileName { get; set; }
        public string ObjectName { get; set; }
        public int PreferredScriptLocation { get; set; }
        public string CDNPath { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
