//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public Journal()
        {
            this.Journal_Data = new HashSet<Journal_Data>();
            this.Journal_Comments = new HashSet<Journal_Comments>();
        }
    
        public int JournalId { get; set; }
        public int JournalTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> PortalId { get; set; }
        public int ProfileId { get; set; }
        public int GroupId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string ItemData { get; set; }
        public string ImageURL { get; set; }
        public string ObjectKey { get; set; }
        public Nullable<System.Guid> AccessKey { get; set; }
        public Nullable<int> ContentItemId { get; set; }
        public bool IsDeleted { get; set; }
        public bool CommentsDisabled { get; set; }
        public bool CommentsHidden { get; set; }
    
        public virtual ICollection<Journal_Data> Journal_Data { get; set; }
        public virtual Journal_Types Journal_Types { get; set; }
        public virtual ICollection<Journal_Comments> Journal_Comments { get; set; }
    }
}
