//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal_Types
    {
        public Journal_Types()
        {
            this.Journals = new HashSet<Journal>();
        }
    
        public int JournalTypeId { get; set; }
        public string JournalType { get; set; }
        public string icon { get; set; }
        public int PortalId { get; set; }
        public bool IsEnabled { get; set; }
        public bool AppliesToProfile { get; set; }
        public bool AppliesToGroup { get; set; }
        public bool AppliesToStream { get; set; }
        public string Options { get; set; }
        public bool SupportsNotify { get; set; }
        public bool EnableComments { get; set; }
    
        public virtual ICollection<Journal> Journals { get; set; }
    }
}
