//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal_Comments
    {
        public int CommentId { get; set; }
        public int JournalId { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CommentXML { get; set; }
    
        public virtual Journal Journal { get; set; }
    }
}
