//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal_TypeFilters
    {
        public int JournalTypeFilterId { get; set; }
        public int PortalId { get; set; }
        public int ModuleId { get; set; }
        public int JournalTypeId { get; set; }
    }
}
