//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.CoreMessaging_Subscriptions = new HashSet<CoreMessaging_Subscriptions>();
            this.HtmlTexts = new HashSet<HtmlText>();
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.ModuleSettings = new HashSet<ModuleSetting>();
            this.TabModules = new HashSet<TabModule>();
        }
    
        public int ModuleID { get; set; }
        public int ModuleDefID { get; set; }
        public bool AllTabs { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> InheritViewPermissions { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.DateTime> LastContentModifiedOnDate { get; set; }
        public Nullable<int> ContentItemID { get; set; }
        public bool IsShareable { get; set; }
        public bool IsShareableViewOnly { get; set; }
    
        public virtual ContentItem ContentItem { get; set; }
        public virtual ICollection<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual ICollection<HtmlText> HtmlTexts { get; set; }
        public virtual ModuleDefinition ModuleDefinition { get; set; }
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual ICollection<ModuleSetting> ModuleSettings { get; set; }
        public virtual ICollection<TabModule> TabModules { get; set; }
    }
}
