//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal
    {
        public Portal()
        {
            this.AnonymousUsers = new HashSet<AnonymousUser>();
            this.CoreMessaging_Subscriptions = new HashSet<CoreMessaging_Subscriptions>();
            this.Files = new HashSet<File>();
            this.FolderMappings = new HashSet<FolderMapping>();
            this.Folders = new HashSet<Folder>();
            this.Mobile_PreviewProfiles = new HashSet<Mobile_PreviewProfiles>();
            this.Mobile_Redirections = new HashSet<Mobile_Redirections>();
            this.PortalAlias = new HashSet<PortalAlia>();
            this.PortalDesktopModules = new HashSet<PortalDesktopModule>();
            this.PortalLanguages = new HashSet<PortalLanguage>();
            this.PortalLocalizations = new HashSet<PortalLocalization>();
            this.PortalSettings = new HashSet<PortalSetting>();
            this.Profiles = new HashSet<Profile>();
            this.ProfilePropertyDefinitions = new HashSet<ProfilePropertyDefinition>();
            this.Relationships = new HashSet<Relationship>();
            this.RoleGroups = new HashSet<RoleGroup>();
            this.Roles = new HashSet<Role>();
            this.SiteLogs = new HashSet<SiteLog>();
            this.SystemMessages = new HashSet<SystemMessage>();
            this.Tabs = new HashSet<Tab>();
            this.Urls = new HashSet<Url>();
            this.UrlTrackings = new HashSet<UrlTracking>();
            this.UserPortals = new HashSet<UserPortal>();
            this.UsersOnlines = new HashSet<UsersOnline>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int PortalID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int UserRegistration { get; set; }
        public int BannerAdvertising { get; set; }
        public Nullable<int> AdministratorId { get; set; }
        public string Currency { get; set; }
        public decimal HostFee { get; set; }
        public int HostSpace { get; set; }
        public Nullable<int> AdministratorRoleId { get; set; }
        public Nullable<int> RegisteredRoleId { get; set; }
        public System.Guid GUID { get; set; }
        public string PaymentProcessor { get; set; }
        public string ProcessorUserId { get; set; }
        public string ProcessorPassword { get; set; }
        public Nullable<int> SiteLogHistory { get; set; }
        public string DefaultLanguage { get; set; }
        public int TimezoneOffset { get; set; }
        public string HomeDirectory { get; set; }
        public int PageQuota { get; set; }
        public int UserQuota { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<int> PortalGroupID { get; set; }
    
        public virtual ICollection<AnonymousUser> AnonymousUsers { get; set; }
        public virtual ICollection<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<FolderMapping> FolderMappings { get; set; }
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual ICollection<Mobile_PreviewProfiles> Mobile_PreviewProfiles { get; set; }
        public virtual ICollection<Mobile_Redirections> Mobile_Redirections { get; set; }
        public virtual ICollection<PortalAlia> PortalAlias { get; set; }
        public virtual ICollection<PortalDesktopModule> PortalDesktopModules { get; set; }
        public virtual ICollection<PortalLanguage> PortalLanguages { get; set; }
        public virtual ICollection<PortalLocalization> PortalLocalizations { get; set; }
        public virtual ICollection<PortalSetting> PortalSettings { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<ProfilePropertyDefinition> ProfilePropertyDefinitions { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<RoleGroup> RoleGroups { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<SiteLog> SiteLogs { get; set; }
        public virtual ICollection<SystemMessage> SystemMessages { get; set; }
        public virtual ICollection<Tab> Tabs { get; set; }
        public virtual ICollection<Url> Urls { get; set; }
        public virtual ICollection<UrlTracking> UrlTrackings { get; set; }
        public virtual ICollection<UserPortal> UserPortals { get; set; }
        public virtual ICollection<UsersOnline> UsersOnlines { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
