//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public Relationship()
        {
            this.UserRelationshipPreferences = new HashSet<UserRelationshipPreference>();
            this.UserRelationships = new HashSet<UserRelationship>();
        }
    
        public int RelationshipID { get; set; }
        public int RelationshipTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int DefaultResponse { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedOnDate { get; set; }
    
        public virtual Portal Portal { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserRelationshipPreference> UserRelationshipPreferences { get; set; }
        public virtual ICollection<UserRelationship> UserRelationships { get; set; }
    }
}
