//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.DesktopModulePermissions = new HashSet<DesktopModulePermission>();
            this.FolderPermissions = new HashSet<FolderPermission>();
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.TabPermissions = new HashSet<TabPermission>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int RoleID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public string BillingFrequency { get; set; }
        public Nullable<int> TrialPeriod { get; set; }
        public string TrialFrequency { get; set; }
        public Nullable<int> BillingPeriod { get; set; }
        public Nullable<decimal> TrialFee { get; set; }
        public bool IsPublic { get; set; }
        public bool AutoAssignment { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public string RSVPCode { get; set; }
        public string IconFile { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public int Status { get; set; }
        public int SecurityMode { get; set; }
        public bool IsSystemRole { get; set; }
    
        public virtual ICollection<DesktopModulePermission> DesktopModulePermissions { get; set; }
        public virtual ICollection<FolderPermission> FolderPermissions { get; set; }
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual Portal Portal { get; set; }
        public virtual RoleGroup RoleGroup { get; set; }
        public virtual ICollection<TabPermission> TabPermissions { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
