//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMng
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<bool> Return { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
    }
}
