//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateType
    {
        public StateType()
        {
            this.States = new HashSet<State>();
        }
    
        public string ID { get; set; }
        public string types { get; set; }
        public Nullable<int> Usage { get; set; }
    
        public virtual ICollection<State> States { get; set; }
    }
}
