//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccouunt
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Passkey { get; set; }
        public Nullable<int> RoleID { get; set; }
        public byte[] ProfileImage { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastTimeOnline { get; set; }
    
        public virtual UserAccouuntsRole UserAccouuntsRole { get; set; }
    }
}
