//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ContentWorkflowStatePermissions = new HashSet<ContentWorkflowStatePermission>();
            this.CoreMessaging_Subscriptions = new HashSet<CoreMessaging_Subscriptions>();
            this.DesktopModulePermissions = new HashSet<DesktopModulePermission>();
            this.FolderPermissions = new HashSet<FolderPermission>();
            this.ModulePermissions = new HashSet<ModulePermission>();
            this.PasswordHistories = new HashSet<PasswordHistory>();
            this.Profiles = new HashSet<Profile>();
            this.Relationships = new HashSet<Relationship>();
            this.RolesMngs = new HashSet<RolesMng>();
            this.States = new HashSet<State>();
            this.TabPermissions = new HashSet<TabPermission>();
            this.UserAuthentications = new HashSet<UserAuthentication>();
            this.UserPortals = new HashSet<UserPortal>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.UserRelationshipPreferences = new HashSet<UserRelationshipPreference>();
            this.UserRelationships = new HashSet<UserRelationship>();
            this.UserRelationships1 = new HashSet<UserRelationship>();
            this.UserRoles = new HashSet<UserRole>();
            this.UsersOnlines = new HashSet<UsersOnline>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsSuperUser { get; set; }
        public Nullable<int> AffiliateId { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public bool UpdatePassword { get; set; }
        public string LastIPAddress { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public Nullable<System.Guid> PasswordResetToken { get; set; }
        public Nullable<System.DateTime> PasswordResetExpiration { get; set; }
        public string LowerEmail { get; set; }
    
        public virtual ICollection<ContentWorkflowStatePermission> ContentWorkflowStatePermissions { get; set; }
        public virtual ICollection<CoreMessaging_Subscriptions> CoreMessaging_Subscriptions { get; set; }
        public virtual ICollection<DesktopModulePermission> DesktopModulePermissions { get; set; }
        public virtual ICollection<FolderPermission> FolderPermissions { get; set; }
        public virtual ICollection<ModulePermission> ModulePermissions { get; set; }
        public virtual ICollection<PasswordHistory> PasswordHistories { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<RolesMng> RolesMngs { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<TabPermission> TabPermissions { get; set; }
        public virtual ICollection<UserAuthentication> UserAuthentications { get; set; }
        public virtual ICollection<UserPortal> UserPortals { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UserRelationshipPreference> UserRelationshipPreferences { get; set; }
        public virtual ICollection<UserRelationship> UserRelationships { get; set; }
        public virtual ICollection<UserRelationship> UserRelationships1 { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UsersOnline> UsersOnlines { get; set; }
    }
}
