//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amirhome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccouuntsRole
    {
        public UserAccouuntsRole()
        {
            this.UserAccouunts = new HashSet<UserAccouunt>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public Nullable<int> AccessLevel { get; set; }
    
        public virtual ICollection<UserAccouunt> UserAccouunts { get; set; }
    }
}
